# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"unpickle_cifar": "01_dataloader.ipynb",
         "load_label_names": "01_dataloader.ipynb",
         "normalize": "01_dataloader.ipynb",
         "one_hot_encoding": "01_dataloader.ipynb",
         "CifarDownloadedDataset": "01_dataloader.ipynb"}

modules = ["dataloader.py"]

doc_url = "https://jjmachan.github.io/Cifar_pytorch/"

git_url = "https://github.com/jjmachan/Cifar_pytorch/tree/master/"

def custom_doc_links(name): return None
