# AUTOGENERATED! DO NOT EDIT! File to edit: 02_train.ipynb (unless otherwise specified).

__all__ = ['eval_model_accuracy']

# Cell
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np

from Cifar_pytorch import dataloader

# Cell
def eval_model_accuracy(model, loader):
    with torch.no_grad():
        total = 0
        correct = 0
        for images, labels in loader:
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
        print('\n\n Accuracy: %.3f \n\n'%(correct * 100/total))